project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "BEE 4750 - Fall 2023"
  description: "Homepage for BEE 4750/57e50, Environmental Systems Analysis, at Cornell University, Fall 2023."
  site-url: "https://bee4750.github.io/fall2023"

  repo-url: https://github.com/BEE4750/fall2023
  repo-actions: [edit, issue]

  open-graph: true


  page-footer:
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

    left: |
      Content {{< fa copyright >}} {{< var course.copyright_year >}}  by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}).
      See the [About page](/about.html) for credit information.<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

  sidebar:
    style: docked
    align: center
    logo: _assets/logos/cornell-reduced-red.svg
    title: "{{< var course.number >}}"
    search: true
    tools: 
      - icon: github
        href: https://github.com/vsrikrish/environmental-systems-analysis
        text: "Github Repository"
      - icon: journal-check
        href: https://canvas.cornell.edu
        text: "Canvas"
      - icon: chat-fill
        text: "Ed Discussion"
        url: https://edstem.org
      - icon: bar-chart-fill
        text: "Gradescope"
        url: https://gradescope.com
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          - href: index.qmd
            text: Overview
          - href: schedule.qmd
            text: Schedule
          - href: syllabus.qmd
            text: Syllabus
      - section: hw.qmd
        contents:
          - href: hw/hw01/hw01.qmd
            text: Homework 1
          - href: hw/hw02/hw02.qmd
            text: Homework 2
          - href: hw/hw03/hw03.qmd
            text: Homework 3
          - href: hw/hw04/hw04.qmd
            text: Homework 4
          - href: hw/hw05/hw05.qmd
            text: Homework 5
      - section: labs.qmd
        contents:
          - href: labs/lab01/lab01.qmd
            text: Lab 1
          - href: labs/lab02/lab02.qmd
            text: Lab 2
          - href: labs/lab03/lab03.qmd
            text: Lab 3          
          - href: labs/lab04/lab04.qmd
            text: Lab 4
      - text: "Final Project" 
        href: project.qmd
      - text: "Tools Setup"
        href: setup.qmd
      - text: "FAQ"
        href: faq.qmd
      - section: "Tutorials"
        contents:
          - href: tutorials/julia-basics.qmd
            text: Julia Basics
          - href: tutorials/julia-plots.qmd
            text: Making Plots
          - href: tutorials/latex-notebook.qmd
            text: Math in Notebooks
          - href: tutorials/julia-jump.qmd
            text: Solving Linear Programs
      - section: "Supplemental Notes"
      - section: Resources
        contents:
          - href: resources/julia.qmd
            text: Julia
          - href: resources/github.qmd
            text: GitHub
          - href: resources/markdown.qmd
            text: Markdown
          - href: resources/optimization.qmd
            text: Optimization and Decision-Making


format:
  html:
    theme: 
      [simplex, sass/theme.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select
    html-math-method: mathjax
    include-in-header: mathjax-config.html

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl

jupyter: julia-1.9
execute:
  freeze: auto  